import { ArrayNode } from "../types";

export interface DtoGeneratorConfig {
  detectDates: boolean;
}

export const DEFAULT_CONFIG: DtoGeneratorConfig = {
  detectDates: true,
};

interface TypeResult {
  phpType: string;
  docType?: string; // The specific PHPDoc type (e.g., 'positive-int')
  isObject: boolean;
  objectClassName?: string;
  isDate: boolean;
  isList: boolean;
  listItemType?: string; // The class name of items if this is a list of objects
  isListItemNullable?: boolean; // Track if items in the list can be null
}

interface PropertyDef {
  name: string;
  type: string; // PHP type
  docType?: string; // PHPDoc type
  isNullable: boolean;
  isObject: boolean;
  objectClassName?: string;
  isList: boolean;
  isObjectList: boolean;
  isListItemNullable?: boolean;
  isDate: boolean;
}

interface ClassDefinition {
  name: string;
  properties: PropertyDef[];
}

class DtoGenerator {
  private classes: Map<string, ClassDefinition> = new Map();
  private readonly ISO_DATE_REGEX = /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?)?$/;
  private config: DtoGeneratorConfig;

  constructor(config: DtoGeneratorConfig = DEFAULT_CONFIG) {
    this.config = config;
  }

  public generate(rootNode: ArrayNode): string {
    this.classes.clear();

    const rootClassName = "RootDataDto";
    this.processNode(rootNode, rootClassName);

    const output: string[] = [];
    
    output.push("<?php\n");
    output.push("declare(strict_types=1);\n");
    output.push("// Generated by Array Box Lab");
    output.push("// PHPStan-ready: Strict types, immutable DTOs, and smart PHPDocs\n");

    if (this.classes.size === 0) {
        output.push("// ⚠️ No DTOs generated.");
        output.push("// The input is a simple list or scalar value.");
        output.push("// DTOs are generated for Associative Arrays (Objects).");
        output.push("// Try switching the root to 'Assoc' mode or adding nested objects.");
        return output.join("\n");
    }

    output.push("// Zero-dependency, immutable DTOs with strict hydration\n");

    // Output classes (reverse order roughly puts dependencies first)
    Array.from(this.classes.values()).reverse().forEach((def) => {
      output.push(this.renderClass(def));
    });

    // Add a usage example
    output.push(`// Usage Example:`);
    output.push(`// $data = json_decode($json, true);`);
    output.push(`// $dto = ${rootClassName}::fromArray($data);`);

    return output.join("\n");
  }

  private processNode(node: ArrayNode, suggestedName: string): TypeResult {
    const defaultResult = (type: string): TypeResult => ({ 
      phpType: type, isObject: false, isDate: false, isList: false 
    });
    
    // Helper to apply manual PHPDoc override
    const applyOverride = (res: TypeResult): TypeResult => {
        if (node.phpDocType && node.phpDocType.trim() !== '') {
            return { ...res, docType: node.phpDocType };
        }
        return res;
    };

    // 1. Handle Scalars
    if (node.type === 'string') {
        const val = node.value as string;
        
        // Date detection (unless overridden)
        if (this.config.detectDates && this.ISO_DATE_REGEX.test(val)) {
            return applyOverride({ phpType: 'DateTimeImmutable', isObject: false, isDate: true, isList: false });
        }
        
        // No auto-inference for strings anymore
        return applyOverride({ phpType: 'string', isObject: false, isDate: false, isList: false });
    }

    if (node.type === 'number') {
        const val = Number(node.value);
        const isInt = Number.isInteger(val);
        const phpType = isInt ? 'int' : 'float';
        
        // No auto-inference for integers anymore
        return applyOverride({ phpType, isObject: false, isDate: false, isList: false });
    }

    if (node.type === 'boolean') return applyOverride(defaultResult('bool'));
    if (node.type === 'null') return applyOverride(defaultResult('mixed')); 

    // 2. Handle Arrays
    if (node.type === 'array') {
      
      // Case A: List (Indexed Array)
      if (!node.isAssociative) {
        // Use the listType setting from the node, default to 'array'
        const strategy = node.listType || 'array';

        if (node.children.length === 0) {
            let emptyDoc = 'array<mixed>';
            if (strategy === 'list') emptyDoc = 'list<mixed>';
            if (strategy === 'array-int') emptyDoc = 'array<int, mixed>';

            return applyOverride({ phpType: 'array', docType: emptyDoc, isObject: false, isDate: false, isList: true });
        }
        
        // Analyze first child to determine list type (assuming homogeneity)
        const firstChild = node.children[0];
        const singularName = this.singularize(suggestedName);
        const childResult = this.processNode(firstChild, singularName);
        
        let childDoc = childResult.docType || childResult.phpType;
        
        // Handle list item nullability (e.g. list<string|null>)
        if (firstChild.isNullable) {
            childDoc = `${childDoc}|null`;
        }

        const hasItems = node.children.length > 0;
        let listDoc = '';

        if (strategy === 'list') {
             const prefix = hasItems ? 'non-empty-list' : 'list';
             listDoc = `${prefix}<${childDoc}>`;
        } else if (strategy === 'array-int') {
             const prefix = hasItems ? 'non-empty-array' : 'array';
             listDoc = `${prefix}<int, ${childDoc}>`;
        } else {
             // 'array' -> array<T>
             const prefix = hasItems ? 'non-empty-array' : 'array';
             listDoc = `${prefix}<${childDoc}>`;
        }

        return applyOverride({ 
            phpType: 'array', 
            docType: listDoc, 
            isObject: false, 
            isDate: false, 
            isList: true,
            listItemType: childResult.isObject ? childResult.phpType : undefined,
            isListItemNullable: firstChild.isNullable
        }); 
      }

      // Case B: Associative Array (Object)
      const className = this.registerClass(suggestedName, node);
      // For objects, docType is usually just the class name
      return applyOverride({ 
          phpType: className, 
          isObject: true, 
          objectClassName: className, 
          isDate: false, 
          isList: false 
      });
    }

    return applyOverride(defaultResult('mixed'));
  }

  private registerClass(name: string, node: ArrayNode): string {
    const finalName = this.capitalize(name);
    
    const properties: PropertyDef[] = [];

    node.children.forEach(child => {
      const propName = child.key;
      let childSuggestedName = propName.toLowerCase().endsWith('dto') ? propName : propName + 'Dto';
      
      if (child.type === 'array' && !child.isAssociative) {
         childSuggestedName = this.singularize(propName) + 'Dto';
      }

      const result = this.processNode(child, childSuggestedName);
      
      const isExplicitlyNullable = child.isNullable === true;
      const isValueNull = (child.value === null && child.type !== 'null' && child.type !== 'array');
      const isTypeNull = child.type === 'null';
      
      const isNullable = isExplicitlyNullable || isValueNull || isTypeNull;
      
      let type = isNullable && result.phpType !== 'mixed' ? `?${result.phpType}` : result.phpType;
      
      if (child.type === 'array' && isNullable) {
         type = `?${result.phpType}`;
      }

      let docType = result.docType;
      
      let isObjectList = false;
      let objectClassName: string | undefined = undefined;

      // Identify if this property is a list of objects that needs simple hydration
      if (result.isList && result.listItemType && this.classes.has(result.listItemType)) {
          isObjectList = true;
          objectClassName = result.listItemType;
      }
      
      if (isNullable && docType) {
          docType = `${docType}|null`;
      }

      // Only add PHPDoc if it adds value (e.g. generics, specific integers) or differs from PHP type
      const isSpecialDoc = docType && (docType !== type && docType.replace('|null', '') !== type.replace('?', ''));

      properties.push({
        name: propName,
        type,
        docType: isSpecialDoc ? docType : undefined,
        isNullable,
        isObject: result.isObject,
        objectClassName: result.objectClassName,
        isList: result.isList,
        isObjectList,
        isListItemNullable: result.isListItemNullable,
        isDate: result.isDate
      });
    });

    this.classes.set(finalName, { name: finalName, properties });
    return finalName;
  }

  private renderClass(def: ClassDefinition): string {
    const propsCode = def.properties.map(p => {
        const doc = p.docType ? `\n    /** @var ${p.docType} */` : '';
        return `${doc}\n    public ${p.type} $${p.name},`;
    }).join('');

    const hydrationCode = def.properties.map(p => {
        const key = `'${p.name}'`;
        const access = `$data[${key}]`;
        const nullCheck = p.isNullable ? `(${access} ?? null)` : access;
        
        let assignment = '';

        if (p.isObject) {
            if (p.isNullable) {
                assignment = `isset($data[${key}]) ? ${p.objectClassName}::fromArray($data[${key}]) : null`;
            } else {
                assignment = `${p.objectClassName}::fromArray(${access})`;
            }
        } else if (p.isObjectList && p.objectClassName) {
            const itemNullable = p.isListItemNullable;
            const mapFnArgs = itemNullable ? `mixed $i` : `array $i`;
            const mapFnBody = itemNullable 
                ? `$i ? ${p.objectClassName}::fromArray($i) : null` 
                : `${p.objectClassName}::fromArray($i)`;
            const mapFn = `fn(${mapFnArgs}) => ${mapFnBody}`;

            if (p.isNullable) {
               assignment = `isset($data[${key}]) ? array_map(${mapFn}, $data[${key}]) : null`;
            } else {
               assignment = `array_map(${mapFn}, ${access})`;
            }
        } else if (p.isDate) {
            if (p.isNullable) {
                assignment = `isset($data[${key}]) ? new DateTimeImmutable($data[${key}]) : null`;
            } else {
                assignment = `new DateTimeImmutable(${access})`;
            }
        } else {
            assignment = nullCheck;
        }

        return `            ${p.name}: ${assignment},`;
    }).join('\n');

    return `
final readonly class ${def.name}
{
    public function __construct(${propsCode}
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
${hydrationCode}
        );
    }
}`;
  }

  private capitalize(s: string): string {
    return s.replace(/(?:^|_)(\w)/g, (_, c) => c.toUpperCase()).replace(/Dto$/i, '') + 'Dto';
  }

  private singularize(s: string): string {
    if (s.endsWith('ies')) return s.slice(0, -3) + 'y';
    if (s.endsWith('s')) return s.slice(0, -1);
    return s;
  }
}

export const generatePhpDto = (rootNode: ArrayNode, config?: Partial<DtoGeneratorConfig>): string => {
  const finalConfig = { ...DEFAULT_CONFIG, ...config };
  const generator = new DtoGenerator(finalConfig);
  return generator.generate(rootNode);
};